name: florian_emails
channels:
- anaconda
- conda-forge
- defaults
dependencies:
- gensim=3.0.1
- appnope=0.1.0=py35_0
- asn1crypto=0.22.0=py35_0
- backports=1.0=py35_1
- backports.functools_lru_cache=1.4=py35_1
- bleach=2.0.0=py35_0
- blinker=1.4=py35_0
- ca-certificates=2017.7.27.1=0
- certifi=2017.7.27.1=py35_0
- cffi=1.10.0=py35_0
- chardet=3.0.4=py35_0
- click=6.7=py35_0
- cryptography=2.0.3=py35_0
- cycler=0.10.0=py35_0
- decorator=4.1.2=py35_0
- entrypoints=0.2.3=py35_1
- flask=0.12.2=py35_0
- freetype=2.7=1
- html5lib=0.999999999=py35_0
- idna=2.6=py35_1
- ipykernel=4.6.1=py35_0
- ipython=6.2.1=py35_0
- ipython_genutils=0.2.0=py35_0
- itsdangerous=0.24=py_2
- jedi=0.10.2=py35_0
- jinja2=2.9.6=py35_0
- jsonschema=2.6.0=py35_0
- jupyter_client=5.1.0=py35_0
- jupyter_core=4.3.0=py35_0
- libffi=3.2.1=3
- libpng=1.6.28=0
- libsodium=1.0.10=0
- markupsafe=1.0=py35_0
- matplotlib=2.1.0=py35_0
- mistune=0.7.4=py35_0
- nbconvert=5.3.1=py_1
- nbformat=4.4.0=py35_0
- ncurses=5.9=10
- nltk=3.2.5=py_0
- notebook=5.0.0=py35_0
- oauthlib=2.0.6=py_0
- openssl=1.0.2l=0
- pandas=0.20.3=py35_1
- pandoc=1.19.2=0
- pandocfilters=1.4.1=py35_0
- pexpect=4.2.1=py35_0
- pickleshare=0.7.4=py35_0
- pip=9.0.1=py35_0
- prompt_toolkit=1.0.15=py35_0
- ptyprocess=0.5.2=py35_0
- pycparser=2.18=py35_0
- pygments=2.2.0=py35_0
- pyjwt=1.5.3=py_0
- pyopenssl=17.2.0=py35_0
- pyparsing=2.2.0=py35_0
- pysocks=1.6.7=py35_0
- python=3.5.4=0
- python-crfsuite=0.9.2=py35_0
- python-dateutil=2.6.1=py35_0
- pytz=2017.2=py35_0
- pyzmq=16.0.2=py35_2
- readline=6.2=0
- requests=2.18.4=py35_1
- requests-oauthlib=0.8.0=py35_1
- setuptools=36.6.0=py35_1
- simplegeneric=0.8.1=py35_0
- six=1.11.0=py35_1
- smart_open=1.5.3=py35_0
- sqlite=3.13.0=1
- terminado=0.6=py35_0
- testpath=0.3.1=py35_0
- tk=8.5.19=2
- tornado=4.5.2=py35_0
- traitlets=4.3.2=py35_0
- twython=3.6.0=py35_0
- urllib3=1.22=py35_0
- wcwidth=0.1.7=py35_0
- webencodings=0.5=py35_0
- werkzeug=0.12.2=py_1
- wheel=0.30.0=py_1
- xz=5.2.3=0
- zeromq=4.2.1=1
- zlib=1.2.11=0
- boto=2.48.0=py35_0
- bz2file=0.98=py35_0
- mkl=2017.0.3=0
- numpy=1.13.1=py35_0
- scikit-learn=0.19.0=np113py35_0
- scipy=0.19.1=np113py35_0
- pip:
  - backports.functools-lru-cache==1.4
  - ipython-genutils==0.2.0
  - jupyter-client==5.1.0
  - jupyter-core==4.3.0
  - prompt-toolkit==1.0.15
  - smart-open==1.5.3

